### ISSUE TITLE
Error building demos-linux

### ISSUE THREAD

**Issue by punitvara** [veltzer/demos-os-linux#3]
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package libsigc++-2.0-0v5
E: Couldn't find any package by regex 'libsigc++-2.0-0v5'
E: Unable to locate package libboost1.58-dev
E: Couldn't find any package by regex 'libboost1.58-dev'
E: Unable to locate package libboost-thread1.58.0
E: Couldn't find any package by regex 'libboost-thread1.58.0'
E: Unable to locate package libpapi5.4.1
E: Couldn't find any package by regex 'libpapi5.4.1'
E: Unable to locate package templar
E: Unable to locate package linux-image-3.19.0-33-generic-dbgsym
E: Couldn't find any package by regex 'linux-image-3.19.0-33-generic-dbgsym'
E: Unable to locate package linux-image-3.19.0-33-lowlatency-dbgsym
E: Couldn't find any package by regex 'linux-image-3.19.0-33-lowlatency-dbgsym'

I have tried to build project as you suggested in docs. Would you look into this please and update any documentation accordingly. I am using ubuntu version 15.04 (x86_64)

**Comment by veltzer** [comment]
Hi,

There is an issue with this package. I have some demos which require many dependencies. Just build the demos you want:

make src/examples/foo/bar.elf

**Comment by punitvara** [comment]
Thank you . I am interested to contribute in this repo. I will soon start doing it :-)
